In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
file_path ='NPS Dataset Atl 23.12.07.xlsx'
df = pd.read_excel(r"C:\Users\Jonathan.Robison\DOT OST\volpe-proj-VU16A100 - Emerging Mobility\Subgroup Support\Traveler Information Technologies\Enhancing Trip Planning Information\NPS Dataset Alt 23.12.07.xlsx")

In [3]:
df.head()

,NPS Full Name,Simplified Name,Park Alpha,Setting,2012,2016,2019,2022,Jan-19,Feb-19,...,Percent of Road Paved,Total Parking Area (Acres),Miles of Road/Acre,Acre of Parking/Acre,visitation patterns,Access Type,Recent Trans Data Collection Study,Hrly VUStats,FOTSC park,remove
0,Abraham Lincoln Birthplace National Historical...,Abraham Lincoln Birthplace,ABLI,rural,169515,252495,238226,265707,1939,6534,...,100.000000,1.503191,0.002441,0.004363,NaN,NaN,NaN,NaN,NaN,NaN
1,Acadia National Park,Acadia,ACAD,rural,2431052,3303393,3437286,3970260,8532,9154,...,98.962243,40.037856,0.001938,0.000816,2. Seasonal,NaN,NaN,NaN,1.0,NaN
2,Adams National Historical Park,Adams,ADAM,urban,336031,199301,187400,12848,27,179,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
3,African Burial Ground National Monument,African Burial Ground,AFBG,urban,77624,46526,47427,29743,96,1571,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
4,Agate Fossil Beds National Monument,Agate Fossil Beds,AGFO,rural,11824,15555,16657,16357,0,94,...,100.000000,1.922567,0.001270,0.000629,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
X = df.drop('NPS Full Name', axis=1)
y = df['NPS Full Name']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
clf = DecisionTreeClassifier()

In [7]:
clf.fit(X_train, y_train)

TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.

In [9]:
df.head()

,NPS name,Setting,2012,2016,2019,2022,Avg 2003-2022,Size (acres),visitation patterns,Access Type,Recent Trans Data Collection Study,Hrly VUStats,FOTSC park,remove
0,Abraham Lincoln Birthplace National Historical...,rural,169515,252495,238226,265707,2.129555e+05,344.50,NaN,NaN,NaN,NaN,NaN,NaN
1,Acadia National Park,rural,2431052,3303393,3437286,3970260,2.735741e+06,49071.40,2. Seasonal,NaN,NaN,NaN,1.0,NaN
2,Adams National Historical Park,urban,336031,199301,187400,12848,1.850850e+05,23.82,NaN,NaN,NaN,NaN,NaN,NaN
3,African Burial Ground National Monument,urban,77624,46526,47427,29743,5.667331e+04,0.35,NaN,NaN,NaN,NaN,NaN,NaN
4,Agate Fossil Beds National Monument,rural,11824,15555,16657,16357,1.466515e+04,3057.87,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
column_titles = df.columns
print(column_titles)

Index([                          'NPS name',
                                  'Setting',
                                       2012,
                                       2016,
                                       2019,
                                       2022,
                            'Avg 2003-2022',
                            'Size  (acres)',
                     'visitation patterns ',
                              'Access Type',
       'Recent Trans Data Collection Study',
                             'Hrly VUStats',
                               'FOTSC park',
                                   'remove'],
      dtype='object')

In [11]:
df.rename(columns={2012: '2012', 2016:'2016', 2019:'2019', 2022:'2022'},
    inplace=True)

print("\nDataFrame after renaming columns:")
print(df)

DataFrame after renaming columns:
                                              NPS name Setting     2012  \
0    Abraham Lincoln Birthplace National Historical...   rural   169515
1                                 Acadia National Park   rural  2431052
2                       Adams National Historical Park   urban   336031
3              African Burial Ground National Monument   urban    77624
4                  Agate Fossil Beds National Monument   rural    11824
..                                                 ...     ...      ...
383                          Wupatki National Monument   rural   201365
384                          Yellowstone National Park   rural  3447729
385                             Yosemite National Park   rural  3853404
386             Yukon-Charley Rivers National Preserve   rural     1393
387                                 Zion National Park   rural  2973607

        2016     2019     2022  Avg 2003-2022  Size  (acres)  \
0     252495   238226   265707   2.129555e+05         344.50
1    3303393  3437286  3970260   2.735741e+06       49071.40
2     199301   187400    12848   1.850850e+05          23.82
3      46526    47427    29743   5.667331e+04           0.35
4      15555    16657    16357   1.466515e+04        3057.87
..       ...      ...      ...            ...            ...
383   223172   187059   194448   2.160079e+05       35401.83
384  4257177  4020288  3290242   3.542700e+06     2219790.71
385  5028868  4422861  3667550   3.716527e+06      761747.50
386     1146     1114      744   4.042050e+03     2526512.44
387  4295127  4488268  4692417   3.370787e+06      147242.66

    visitation patterns   Access Type  Recent Trans Data Collection Study  \
0                    NaN          NaN                                 NaN
1            2. Seasonal          NaN                                 NaN
2                    NaN          NaN                                 NaN
3                    NaN          NaN                                 NaN
4                    NaN          NaN                                 NaN
..                   ...          ...                                 ...
383          1. Sporadic          NaN                                 NaN
384          2. Seasonal          NaN                                 NaN
385          2. Seasonal          NaN                                 NaN
386                  NaN          NaN                                 NaN
387          2. Seasonal          NaN                                 NaN

     Hrly VUStats  FOTSC park  remove
0             NaN         NaN     NaN
1             NaN         1.0     NaN
2             NaN         NaN     NaN
3             NaN         NaN     NaN
4             NaN         NaN     NaN
..            ...         ...     ...
383           NaN         NaN     NaN
384           NaN         1.0     NaN
385           NaN         1.0     NaN
386           NaN         NaN     NaN
387           NaN         1.0     NaN

[388 rows x 14 columns]

In [12]:
column_titles = df.columns
print(column_titles)

Index(['NPS name', 'Setting', '2012', '2016', '2019', '2022', 'Avg 2003-2022',
       'Size  (acres)', 'visitation patterns ', 'Access Type',
       'Recent Trans Data Collection Study', 'Hrly VUStats', 'FOTSC park',
       'remove'],
      dtype='object')

In [13]:
feature_cols = ['NPS name', 'Setting', '2012', '2016', '2019', '2022', 'Avg 2003-2022',
       'Size  (acres)', 'visitation patterns ',]
x = df[feature_cols]
y = df.label

AttributeError: 'DataFrame' object has no attribute 'label'

In [2]:
type(2012)

int